### ISSUE TITLE
hot.accept callback fires two times

### ISSUE THREAD

**Issue by unlight** [sidorares/hot-module-replacement#2]
Steps to reproduce, `examples/express-hot-routes`:
1. Run server.js with modified code:
```
if (module.hot) {
  module.hot.accept('./routes', () => {
  	console.log('x');
  });
}
```
2. Save `routes.js`

Result: `x` printed 2 times, expected: 1 time.

**Comment by sidorares** [comment]
that's probably `fs.watch` reports changes two times here https://github.com/sidorares/hot-module-replacement/blob/80d7afeb0c37b2c39b6f1257e00cc8125b7b3e9b/index.js#L59

Can you console.log what is eventType each time for you?

Easy solution might be adding some debouncing so that even if you save quickly 2 times in a row `accept` callback only called after last event

**Comment by unlight** [comment]
You are right, it is from fs.watch, found SO discussion https://stackoverflow.com/questions/12978924/fs-watch-fired-twice-when-i-change-the-watched-file
```
// console.log("eventType, filename", eventType, filename) in startWatching()
eventType, filename change routes.js
m C:\tmp\hot-module-replacement\examples\express-hot-routes\routes.js
eventType, filename change routes.js
m C:\tmp\hot-module-replacement\examples\express-hot-routes\routes.js
```

Forgot provides my environment:
hot-module-replacement@3.0.0, node v8.9.0, Win8

**Comment by sidorares** [comment]
I'll probably move to https://github.com/paulmillr/chokidar or at leas add debouncing

Will keep this issue open to track progress

**Comment by unlight** [comment]
Chokidar is heavy.
https://github.com/fgnass/filewatcher probably is more suitable.

**Comment by ghoullier** [comment]
Hi @sidorares !

Is this project still maintained?

**Comment by sidorares** [comment]
Hi @ghoullier ! I use it occasionally myself so answer is more yes than no. Happy to review PRs or answer questions but not very much time to add features on my own

**Comment by ghoullier** [comment]
Thanks for your answer.
I work on a PR to replace fs.watch by chokidar.

**Comment by sidorares** [comment]
> I work on a PR to replace fs.watch by chokidar.

Can you consider filewatcher as @unlight  suggests? I don't have an opinion on any, if something works better than `fs.watch` happy to try
